
server:
  port: 9195   


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultzone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
micorservice:
  inventory-service:
    endpoints:
      endpoint:
        uri:  http://inventory-service/inventory/item/
      
      
     
         
